Repository Mridul-1-Sharma/Hacktoberfest2022-DataStructuresAndAlgorithms, pull requests merged in 2022-10, with the labels that each got.

#5 Added quicksort implementation in C++
  Cpp/quicksort.cpp
Labels: hacktoberfest-accepted

#10 Shell_sort
  Cpp/Shell_sort
Labels: hacktoberfest-accepted

#12 Kruskals_minspanning_tree_function
  Cpp/Kruskals_minspanning_tree_function
Labels: hacktoberfest-accepted

#35 roundrobin
  Cpp/dynamicProgramming/roundrobin
Labels: enhancement, hacktoberfest-accepted

#43 Luhn's Algorithm
  Cpp/Luhn's Algorithm
Labels: hacktoberfest-accepted

#49 permutations_of_a_String.cpp
  Cpp/permutations_of_a_String.cpp
Labels: hacktoberfest-accepted

#52 Create Dijkstra’s Shortest Path Algorithm
  Cpp/Dijkstra’s Shortest Path Algorithm.cpp
Labels: hacktoberfest-accepted

#54 Add: searching problem
  python/searching/Binary_Search.py
  python/searching/Linear_Search.py
Labels: hacktoberfest-accepted

#67 Maximum xor with an element
  Cpp/count smaller number after self.cpp
  InterviewDSA/leetcode/Largest rectangle in histogram.cpp
  InterviewDSA/leetcode/maximum xor with element.cpp
Labels: hacktoberfest-accepted

#71 Diameter-of-a-binary-tree
  Cpp/Binary Trees/Diameter-of-a-Binary-Tree
Labels: hacktoberfest-accepted

#70 added SubarrayWithGivenSum.java in InterviewDSA
  InterviewDSA/leetcode/SubArrayWithGivenSum.java
Labels: hacktoberfest-accepted, hacktoberfest

#73 Level-Order-Traversal
  Cpp/Binary Trees/Level-Order-Traversal
Labels: hacktoberfest-accepted, Hacktoberfest

#74 added feature/program-MergeSortedArrays in java
  InterviewDSA/leetcode/MergeSortedArrays.java
Labels: hacktoberfest-accepted, Hacktoberfest

#78 Create Find_Combination.cpp
  Cpp/Find_Combination.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#79 Add files via upload
  java/Linked List/DoublyCircular.java
  java/Linked List/DoublyLinear.java
  java/Linked List/SinglyCircular.java
  java/Linked List/SinglyLinear.java
Labels: hacktoberfest-accepted, Hacktoberfest

#85 largest number from a given set of numbers
  InterviewDSA/leetcode/largestNumber.py
Labels: hacktoberfest-accepted, Hacktoberfest

#87 Delete a Linked List node at a given position
  .DS_Store
  java/Linked List/DeleteLinkedListNodeAtGivenPosition.java
Labels: hacktoberfest-accepted, Hacktoberfest

#81 Added my contribution
  c/collegeData.c
Labels: hacktoberfest-accepted, Hacktoberfest

#90 Added Substring with Concatenation of All Words Problem and Solution in cpp
  InterviewDSA/leetcode/Substring with Concatenation of All Words.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#89 Added House Robber problem in C++
  InterviewDSA/leetcode/House_Robber.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#92 Added Max Point on a Line Problem and Solution in cpp
  InterviewDSA/leetcode/Max Points on a Line.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#93 Added Permutation Sequence Problem and Solution in cpp
  InterviewDSA/leetcode/Permutation Sequence.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#94 Anagram string in c++
  InterviewDSA/geeksforgeeks/anagram.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#97 Set zero matrix problem in C++
  Cpp/Stock buy and sell.cpp
  Cpp/set matrix zero.cpp
  InterviewDSA/leetcode/House_Robber.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#100 Added break the element problem and solution in cpp
  CP Questions/Codechef/Break the element/Array break.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#104 OrderAgnosticBinarysearch in Java
  java/searching/OrderAgnosticBinarySearch.java
Labels: hacktoberfest-accepted, Hacktoberfest

#105 Create sll.py
  python/sll.py
Labels: hacktoberfest-accepted, Hacktoberfest

#106 Added Cycle Sort Algorithm in Java
  java/sorting/Cycle_sort.java
Labels: hacktoberfest-accepted, Hacktoberfest

#110 Added Combination Sum Problem and Solution cpp
  InterviewDSA/leetcode/Combination Sum.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#112 Added Game of Life problem and Solution cpp
  InterviewDSA/leetcode/Games of Life.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#113 Added Rotate Array Problem and Solution CPP
  InterviewDSA/leetcode/Rotate Array.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#115 Added Longest Happy Prefix Problem and Solution in CPP
  InterviewDSA/leetcode/Longest Happy Prefix.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#116 Added coin change 2 Problem in C++
  Cpp/dynamicProgramming/Coin Change II.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#123 added code from hackerrank and hackerearth
  .DS_Store
  CP Questions/.DS_Store
  CP Questions/HackerEarth/.DS_Store
  CP Questions/HackerEarth/Printing Patterns/Printing patterns.cpp
  CP Questions/HackerEarth/Roy and Coin Boxes/Roy and Coin Boxes.cpp
  CP Questions/HackerEarth/The Cheapest Palindrome/The Cheapest Palindrome.cpp
  CP Questions/HackerRank/.DS_Store
  CP Questions/HackerRank/Beautiful Days At The Movies/Beautiful Days At The Movies.cpp
  CP Questions/HackerRank/Beautiful Days At The Movies/Beautiful Days At The Movies.py
  CP Questions/HackerRank/Beautiful Triplets/Beautiful Triplets.cpp
  CP Questions/HackerRank/Box It!/Box It!.cpp
  CP Questions/HackerRank/Cats and a Mouse/Cats and a Mouse.cpp
  CP Questions/HackerRank/Classes and objects/classes and objects.cpp
  CP Questions/HackerRank/Closest Number/Closest Number.py
  CP Questions/HackerRank/Designer PDF Viewer/Designer PDF Viewer.cpp
  CP Questions/HackerRank/Diagonal Difference/diagonal Difference.cpp
  CP Questions/HackerRank/Diagonal Difference/diagonal Difference.py
  CP Questions/HackerRank/Extra Long Factorials/Extra Long Factorial.cpp
  CP Questions/HackerRank/Extra Long Factorials/Extra Long Factorial.py
  CP Questions/HackerRank/Find Digits/Find Digits.cpp
  CP Questions/HackerRank/Find Digits/Find Digits.java
  CP Questions/HackerRank/Find Digits/Find Digits.js
  CP Questions/HackerRank/Find Digits/Find Digits.py
  CP Questions/HackerRank/Find Median/Find Median.cpp
  CP Questions/HackerRank/Find Median/Find Median.py
  CP Questions/HackerRank/Hotel Prices/Hotel Prices.cpp
  CP Questions/HackerRank/Huffman Decoding/Huffman Decoding.cpp
  CP Questions/HackerRank/Ice Cream Parlor/Ice Cream Parlor.cpp
  CP Questions/HackerRank/Ice Cream Parlor/Ice Cream Parlor.java
  CP Questions/HackerRank/Ice Cream Parlor/Ice Cream Parlor.py
  CP Questions/HackerRank/Inherited code/Inherited code.cpp
  CP Questions/HackerRank/Journey to the Moon/Journey to the Moon.cpp
  CP Questions/HackerRank/Mars Exploration/Mars Exploration.cpp
  CP Questions/HackerRank/Operator Overloading/Operator Overloading.cpp
  CP Questions/HackerRank/Pangrams/Pangrams.cpp
  CP Questions/HackerRank/Pangrams/Pangrams.java
  CP Questions/HackerRank/Sherlock And Permutations/Sherlock And Permutations.cpp
  CP Questions/HackerRank/Strong Password/Strong Password.cpp
  CP Questions/HackerRank/The Hurdle Race/The Hurdle Race.cpp
  CP Questions/HackerRank/Virtual Functions/virtual function.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#129 Polymorphism.java
  java/OOPS/Polymorphism.java
Labels: hacktoberfest-accepted, Hacktoberfest

#130 DynamicMethod.java
  java/OOPS/DynamicMethod.java
Labels: hacktoberfest-accepted, Hacktoberfest

#131 Added conversions
  Cpp/number_systems/binaryToDecimal.cpp
  Cpp/number_systems/decimalToBinary.cpp
  Cpp/number_systems/decimalToHexadecimal.cpp
  Cpp/number_systems/decimalToOctal.cpp
  Cpp/number_systems/hexadecimalToDecimal.cpp
  Cpp/number_systems/octalToDecimal.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#132 InheritanceConcept.java
  java/OOPS/InhertanceConcept.java
Labels: hacktoberfest-accepted, Hacktoberfest

#133 Overloadling.java
  java/Overloading.java
Labels: hacktoberfest-accepted, Hacktoberfest

#134 Added the most popular DP problems
  Dynamic Programming/0-1KnapsackProblem.cpp
  Dynamic Programming/BoxStacking.cpp
  Dynamic Programming/CoinChange.cpp
  Dynamic Programming/CountPalindromicSubsequence.cpp
  Dynamic Programming/EggDropping.cpp
  Dynamic Programming/LongestCommonSubstring.cpp
  Dynamic Programming/LongestPalindromicSubstring.cpp
  Dynamic Programming/MaxLengthChain.cpp
  Dynamic Programming/NthCatalanNumber.cpp
  Dynamic Programming/PalindromicPartitioning.cpp
  Dynamic Programming/ShortestCommonSupersequence.cpp
  Dynamic Programming/SubsetSum.cpp
  Dynamic Programming/UniqueBST.cpp
  Dynamic Programming/WordBreakProblem.cpp
  Dynamic Programming/editDistance.cpp
  Dynamic Programming/lcs.cpp
  Dynamic Programming/lis.cpp
  Dynamic Programming/longestPathMatrix.cpp
  Dynamic Programming/matrixChainMultliplication.cpp
  Dynamic Programming/minimumSumPartition.cpp
  Dynamic Programming/partitionProblem.cpp
  Dynamic Programming/rodCutting.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#136 added maximum path sum problem
  InterviewDSA/leetcode/Binary Trees/max path sum.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#141 Transpose 2D vector.cpp
  InterviewDSA/leetcode/Transpose 2D vector.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#142 Remove Duplicate number.cpp
  InterviewDSA/leetcode/Remove Duplicate number.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#145 Create calculator.java
  java/calculator.java
Labels: hacktoberfest-accepted, Hacktoberfest

#146 Added an ML Project (python) in Python folder
  python/ML Project/Image augmentation in Python
  python/ML Project/Image4.jpg
Labels: hacktoberfest-accepted, Hacktoberfest

#148 Added code for converting a linked list to hashset
  java/Linked List/HashSetWithLinkedList.java
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#149 Added Remove Nth Node From End of List Problem in C++
  Cpp/Remove Nth Node From End of List.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#143 Contribution in c code
  c/studata.c
Labels: hacktoberfest-accepted, Hacktoberfest

#151 Added 4Sum Problem in C++
  Cpp/4Sum.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#152 Removed some duplicate code and added code for linear search
  Cpp/Searching/LinearSearch.cpp
  Cpp/Sorting/quicksort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#153 palindrome Number.cpp
  InterviewDSA/leetcode/palindrome Number.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#154 Create PrintSubSequence.cpp
  Cpp/PrintSubSequence.cpp
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#156 Added a program to Check if a string is interleaving of two other giv…
  Dynamic Programming/string_interleaving.cpp
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#157 Added Strassen's algorithm for matrix multiplication in C
  c/Strassensalgo.c
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#158 Create reverse_of_array.cpp
  reverse_of_array.cpp
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#159 Added
  NumberConversion/BaseToOthers.class
  NumberConversion/BaseToOthers.java
  NumberConversion/Number.class
Labels: hacktoberfest-accepted, Hacktoberfest

#160 Add files via upload
  Cpp/Sorting/sorted population.cpp
  Cpp/Sorting/sorting_techniques.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#161 Median of Two Sorted Arrays.cpp added
  InterviewDSA/leetcode/Hacktoberfest2022-DataStructuresAndAlgorithms.code-workspace
  InterviewDSA/leetcode/MedianofTwoSortedArrays.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#162 Go added
  Go/stack/stack.go
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#164 Radix Sort
  c/sorting/RadixSort.c
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#165 Added Leetcode problem number 35 search insert element
  InterviewDSA/leetcode/search_insert_element.java
Labels: hacktoberfest-accepted, Hacktoberfest

#167 Added Spiral Traversal of Binary tree
  Cpp/Binary Trees/spiral Order traversal of tree.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#168 added Pow(x, n) problem in Java
  java/Pow(x, n).java
Labels: hacktoberfest-accepted, Hacktoberfest

#174 Add ReverseString.java
  java/Strings/ReverseString.java
Labels: hacktoberfest-accepted, Hacktoberfest

#175 Create many beautiful designs using python turtle
  python/Many Beautiful Designs/Many_beautiful_designs.py
Labels: hacktoberfest-accepted, Hacktoberfest

#176 Update BinarySearch.cpp
  Cpp/Searching/BinarySearch.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#177 Added Codechef Suspense String Solution
  Suspense_String.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#178 Create Radix_Sort.java
  java/sorting/Radix_Sort.java
Labels: hacktoberfest-accepted, Hacktoberfest

#179 Added the code for Bucket_Sort
  Cpp/Sorting/Bucket_Sort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#182 Distance of desired position from the first iterator in array.cpp
  Cpp/Distance of desired position from the first iterator in array.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#183 If given linked list is palindrome or not
  Cpp/Basic Problems/checkIfLinkedListIsPalindrome.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#184 Added Word Search Problem in Java
  java/Word Search.java
Labels: hacktoberfest-accepted, Hacktoberfest

#185 Added Longest Increasing Subsequence Problem in C++
  Cpp/Longest Increasing Subsequence.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#186 GeneralFlexibleArray - Data Structure
  Cpp/Array - Data Structure/GeneralFlexibleArray.cpp
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#187 Insertion in Circular LinkedList
  InterviewDSA/leetcode/insertion_in_cll.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#189 Created Minimum Depth of Binary Tree.cpp
  Cpp/Binary Trees/Minimum Depth of Binary Tree.cpp
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#190 added
  Cpp/InterviewDSA/Best time to buy and sell stock.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#191 Added code for Fibonacci Search
  Cpp/Searching/ExponentialSearch.cpp
  Cpp/Searching/FibonacciSearch.cpp
Labels: Hacktoberfest

#199 Create 3SumClosest.cpp
  Cpp/3SumClosest.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#200 Created twosum.cpp
  Cpp/twosum.cpp
Labels: hacktoberfest-accepted, Hacktoberfest

#201 Created Path Sum.cpp
  Cpp/Binary Trees/Path Sum.cpp
Labels: hacktoberfest-accepted, Hacktoberfest
